### PR TITLE
Update nom to 4

### PR DESCRIPTION
**Pull request by jhoobergs**
With this change, dvi-rs can be used to compile rust to wasm.
Nom 4 uses a newer version of memchr.
see https://github.com/Geal/nom/issues/633

(updating to later versions of nom should also be possible, but this is the minimum needed to use it in wasm)

(there are also a lot of style changes)

### CODE REVIEW

**Comment by richard-uk1** [comment]
Thanks for this. I will probably apply `cargo fmt` and then rebase your changes against that, to reduce the size of the diff. This might mean that I end up manually merging your PR rather than accepting it. I'll comment on here if this happens.

**Comment by richard-uk1** [comment]
I've manually merged this PR, and made a new release (0.2). Thanks for the contribution!

**Comment by richard-uk1** [comment]
In fact I ended up updating `nom` to v5.

**Comment by jhoobergs** [comment]
Great. Thanks!

**Pull request closed without merging**
